apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-conf
  labels:
    app: {{ template "fullname" . }}-conf
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  custom-config.conf: |-
    server {
      listen 0.0.0.0:{{ .Values.nginxService.internalPort }};
      client_max_body_size 108M;
      root /usr/share/nginx/html;
      index index.html index.php;

      if (!-e $request_filename) {
         rewrite ^.*$ /index.php last;
      }

      location ~ \.php$ {
        fastcgi_pass {{ template "fullname" . }}-phpfpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        include fastcgi_params;

      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-phpconf-overrides
  labels:
    app: {{ template "fullname" . }}-phpconf-overrides
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  php-ini-overrides.ini: |-
{{ .Files.Get "files/php-ini-overrides.ini" | indent 4 }}
