apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentPublicVolume }}
  labels:
    type: local
    app: {{ template "fullname" . }}-nginx
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentPublicVolumeLocalStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentPublicVolumeClaim }}
  labels:
    app: {{ template "fullname" . }}-nginx
spec: 
  storageClassName: standard
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi

