apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.php.persistentPublicVolumePhp }}
  labels:
    type: local
    app: {{ template "fullname" . }}-php
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.php.persistentPublicVolumeLocalStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.php.persistentPublicVolumeClaimPhp }}
  labels:
    app: {{ template "fullname" . }}-php
spec: 
  storageClassName: standard
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi

