apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-phpfpm
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - port: {{ .Values.phpfpmService.phpfpmPort  }}
  selector:
    app: {{ template "fullname" . }}-phpfpm
  clusterIP: None
