apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ include "mysql.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mysql.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                key:  mysql_root_password
                name: {{ .Release.Name }}-auth
          - name: "MYSQL_USER"
            valueFrom:
              secretKeyRef:
                key:  mysql_user
                name: {{ .Release.Name }}-auth
          - name: "MYSQL_PASSWORD"
            valueFrom:
              secretKeyRef:
                key:  mysql_password
                name: {{ .Release.Name }}-auth
          - name: "MYSQL_DATABASE"
            valueFrom:
              secretKeyRef:
                key:  mysql_database
                name: {{ .Release.Name }}-auth
 
        ports:
        - containerPort: {{ .Values.mysqlService.port }}
          name: mysql
        volumeMounts:
        - name: mysql-overrides
          mountPath: /etc/mysql/conf.d/mysql.cnf
          subPath: mysql.cnf
        - mountPath: /docker-entrypoint-initdb.d
          name: {{ .Values.persistentVolumeInitdbName }}
        - mountPath: {{ .Values.persistentVolumeMountPath }}
          name: {{ .Values.persistentVolumeClaim }}  
      volumes:
      - name: mysql-overrides
        configMap:
          name: {{ include "mysql.name" . }}-mysql-overrides
          items:
          - key: mysql.cnf
            path: mysql.cnf
      - name: mysql-data-disk
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim }}
      - name: {{ .Values.persistentVolumeInitdbName }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeInitdbClaim }}
