apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolumeInitdbVolume }}
  labels:
    type: local
    app: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistentVolumeInitdbMountPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeInitdbClaim }}
  labels: 
    app: mysql
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
