---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
type: Opaque
data:
  mysql_root_password: {{ .Values.mysql_root_password | b64enc | quote }}
  mysql_user: {{ .Values.mysql_user | b64enc | quote }}
  mysql_password: {{ .Values.mysql_password | b64enc | quote }}
  mysql_database: {{ .Values.mysql_database | b64enc | quote }}
