apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: {{ .Values.mysqlService.port }}
  selector:
    app: {{ include "mysql.name" . }}
  clusterIP: None
